[package]
name = "lininterp"
version = "0.1.0"
authors = ["dobkeratops <dobkeratopsgit@gmail.com>"]
description = "generic linear interpolation, should support dimension checking types etc"
keywords=["lerp","invlerp","dimension checking","maths","interpolation"]
license = "MIT"
repository = "https://github.com/dobkeratops/lininterp"

[dependencies]
